name: Release to candidate
on:
  workflow_dispatch
jobs:
  candidatePromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: prod-beta
      - name: Reset promotion branch
        run: |
          git fetch origin master:master
          git reset --hard master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: candidate-promotion
          title: Release to candidate (prod-beta)
          delete-branch: true
          labels: release/sync-up
          reviewers: gkarat